### PR TITLE
Remove Python 3.3 classifier

### PR DESCRIPTION
**Pull request by sloria**
Tests aren't run against Python 3.3

### CODE REVIEW

**Comment by sloria** [comment]
Btw, I recommend also dropping support for Python 3.4. It's over 5 years old at this point.

**Comment by blag** [comment]
Yep, I just noticed that too (and the tests for my version bump PR were taking too long).

I'm going to be busy the rest of today, but if you feel inclined, I would definitely eventually review/merge one or more PRs that:

* [ ] removed Python 3.4 from the CI tests
* [ ] removed Django 1.9 and 1.10 configs
* [ ] added Django 2+ configs
* [ ] added Python 3.7+ configs
* [ ] added support for coverage

I'll try to get around to reviewing/merging those PRs tomorrow.

And at some point, likely on, around, or after January 1st, 2020, I plan on completely removing support and all compatibility modules for Python <= 2.7, as well as transitioning off of using six. Python 3 all the way. 😃

**Comment by sloria** [comment]
Great. I won't have time to do that myself. 

Thanks for the maintenance work you're doing .

**Comment by sloria** [comment]
Incidentally, I've been working on dropping Python 2 in my libs. Made a checklist today: https://gist.github.com/sloria/b4a5fc2281f86a5733af198d609c5ab3 . Some of the things are fairly specific to my projects, but may be helpful anyway.

Onward to py3!

**Comment by blag** [comment]
I'll try to work on my TODO list either tomorrow or sometime next week, including merging this PR. Testing a lot of different uses is great, but I also want to minimize the amount of testing we do for configurations that are already EOLed.

**Comment by blag** [comment]
Thanks for this!

**Pull request merged**
