### PR TITLE
serialize values as json before counting.

### LINKED ISSUE #97: Unique constraint on arrays containing objects raises exception
We have a response for an endpoint defined as follows in our spec:
```
        responses:
          200:
            description: list of payment methods
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: array
                  uniqueItems: true
                  items:
                    $ref: '#/definitions/PaymentMethod'
```
The important thing to note is that `data` here is an array containing objects. When validating a response from this endpoint, we get this exception raised:
```
 TypeError: unhashable type: 'dict'
```
I'm thinking that this is because when validating uniqueness, flex uses a counter [here](https://github.com/pipermerriam/flex/blob/a8ddfae3393aea596b390022bb7263d2ca408937/flex/validation/common.py#L244), which [requires hashable types](https://docs.python.org/2/library/collections.html#collections.Counter).

Here's the full stacktrace:
```
 /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/validation/response.py line 241 in validate_response
      response_validator(response, context=schema)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/validation/common.py line 322 in validate_object
      schema_validators.validate_object(obj, context=context)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 75 in validate_object
      validator(obj, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 46 in __call__
      return self.validate_object(*args, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 41 in validate_object
      validator(obj, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/functional.py line 9 in chain_reduce
      value = function(value, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/validation/common.py line 322 in validate_object
      schema_validators.validate_object(obj, context=context)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 75 in validate_object
      validator(obj, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 46 in __call__
      return self.validate_object(*args, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 41 in validate_object
      validator(obj, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/decorators.py line 52 in inner
      return func(value, *args, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/decorators.py line 37 in inner
      return func(value, *args, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/functional.py line 9 in chain_reduce
      value = function(value, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/validation/common.py line 322 in validate_object
      schema_validators.validate_object(obj, context=context)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 75 in validate_object
      validator(obj, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 46 in __call__
      return self.validate_object(*args, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/datastructures.py line 41 in validate_object
      validator(obj, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/decorators.py line 52 in inner
      return func(value, *args, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/decorators.py line 37 in inner
      return func(value, *args, **kwargs)
    /app/shared/virtualenvs/venmo_platform27/local/lib/python2.7/site-packages/flex/validation/common.py line 245 in validate_unique_items
      (v, type(v)) for v in value
    /usr/lib/python2.7/collections.py line 419 in __init__
      self.update(iterable, **kwds)
    /usr/lib/python2.7/collections.py line 501 in update
      self[elem] = self_get(elem, 0) + 1
   TypeError: unhashable type: 'dict'
```

### PR DESCRIPTION
**Pull request by amygdalama**
Fixes #97.

Edit:
image

### CODE REVIEW

**Comment by pipermerriam** [comment]
Can you add [`sort_keys=True`](https://docs.python.org/2/library/json.html#json.dumps) to the `json.dumps` since the ordering of dictionaries isn't defined.  That way if the same dictionary is present we can be sure that it didn't get serialized as two different strings because of the key ordering.

**Comment by amygdalama** [comment]
Ready for another look. It isn't obvious to me how to add a test for this case -- want one? I'm not sure if I can guarantee different key ordering.

**Comment by pipermerriam** [comment]
You could probably trigger the error using an OrderedDict from the `collections` library to force two dictionaries to have different key ordering.

**Comment by amygdalama** [comment]
Good idea -- used `OrderedDict` for the test and amended it to my last commit. It fails without the `sort_keys=True` change.

**Comment by pipermerriam** [comment]
Thanks for an easy PR.  Getting a release up on pypi now.

**Comment by amygdalama** [comment]
:+1: thanks for the responses and suggestions!

**Pull request merged**
