### PR TITLE
fix ContactObject and LicenseObject validation

### PR DESCRIPTION
**Pull request by pipermerriam**
### What is the problem / feature ?
- Flex did not properly validate the LicenseObject
- Flex did not properly validate the ContactObject
- Flex did not have the correct type options for parameter types.
- Flex did not correctly validate the `default` keyword.
### How did it get fixed / implemented ?
- Changed the validation to conform to the License and Contact object specs.
  - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#contactObject
  - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#license-object
- Added `file` as a valid type for parameter types.
- Removed validation of the `default` keyword.
### How can someone test / see it ?

Try to validate the pet store schema provided by swagger at http://petstore.swagger.io/v2/swagger.json

_Here is a cute animal picture for your troubles..._
images

### CODE REVIEW

**Comment by pipermerriam** [comment]
cc #76

**Comment by pipermerriam** [comment]
It looks like my original interpretation of the default keyword may have been mostly correct.  Conversation happening in #76

**Comment by pipermerriam** [comment]
Pending discussion on https://github.com/swagger-api/swagger-spec/issues/343 as to wheter 00d45c6 should be included in this PR.

**Comment by marcosscriven** [comment]
Just hit this issue validating a ```contact``` object.

**Comment by allan-simon** [comment]
would it be possible to extract the part about "LicenseObject" in a separate PR ?

**Comment by yohanboniface** [comment]
Also interested by a fix for the LicenseObject parsing. Any way I can help?

**Comment by pipermerriam** [comment]
I'll be happy to look over/merge/release this if someone wants to prepare the pull request

**Pull request closed without merging**
